// gen-icons reads icons.templ for Icon* function names, loads matching SVGs from
// node_modules/lucide-static/icons/, and regenerates:
//   - static/icons.svg (SVG sprite with all symbols)
//   - internal/ui/components/icons.templ (<use> wrappers referencing the sprite)
//   - frontend/js/icons.js (exported JS functions)
//
// To add an icon: append "templ IconNewName() {}" to icons.templ, then re-run.
// Name convention: IconGripVertical → grip-vertical.svg (PascalCase → kebab-case).
//
// Usage: go run ./cmd/gen-icons
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

type iconData struct {
	name, file, inner string
}

var (
	commentRE  = regexp.MustCompile(`(?s)<!--.*?-->`)
	innerRE    = regexp.MustCompile(`(?s)<svg[^>]*>(.*)</svg>`)
	funcNameRE = regexp.MustCompile(`(?m)^templ (Icon\w+)\(\)`)
)

func extractInner(raw string) string {
	s := commentRE.ReplaceAllString(raw, "")
	m := innerRE.FindStringSubmatch(s)
	if len(m) < 2 {
		return ""
	}
	return strings.TrimSpace(m[1])
}

// toKebab converts PascalCase to kebab-case: GripVertical → grip-vertical.
func toKebab(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if i > 0 && unicode.IsUpper(r) {
			b.WriteByte('-')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

func iconID(file string) string {
	return "icon-" + file
}

func main() {
	root := findRoot()
	svgPath := filepath.Join(root, "static", "icons.svg")
	templPath := filepath.Join(root, "internal", "ui", "components", "icons.templ")
	jsPath := filepath.Join(root, "frontend", "js", "icons.js")
	iconsDir := filepath.Join(root, "node_modules", "lucide-static", "icons")

	// Parse icons.templ for existing Icon* function names.
	src, err := os.ReadFile(templPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading icons.templ: %v\n", err)
		os.Exit(1)
	}
	matches := funcNameRE.FindAllSubmatch(src, -1)
	if len(matches) == 0 {
		fmt.Fprintln(os.Stderr, "no Icon* functions found in icons.templ")
		os.Exit(1)
	}

	data := make([]iconData, 0, len(matches))
	for _, m := range matches {
		name := string(m[1])                 // e.g. "IconGripVertical"
		file := toKebab(name[len("Icon"):]) // e.g. "grip-vertical"
		raw, err := os.ReadFile(filepath.Join(iconsDir, file+".svg"))
		if err != nil {
			fmt.Fprintf(os.Stderr, "error reading %s.svg (from %s): %v\n", file, name, err)
			os.Exit(1)
		}
		data = append(data, iconData{name: name, file: file, inner: extractInner(string(raw))})
	}

	writeIconsSVG(svgPath, data)
	writeIconsTempl(templPath, data)
	writeIconsJS(jsPath, data)
}

const useAttrs = `class="icon" aria-hidden="true"`

func writeIconsSVG(path string, data []iconData) {
	var b strings.Builder
	b.WriteString(`<svg xmlns="http://www.w3.org/2000/svg" style="display:none">` + "\n")
	for _, d := range data {
		fmt.Fprintf(&b, `  <symbol id=%q viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">%s</symbol>`+"\n",
			iconID(d.file), d.inner)
	}
	b.WriteString("</svg>\n")
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing icons.svg: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote", path)
}

func writeIconsTempl(path string, data []iconData) {
	var b strings.Builder
	b.WriteString("package components\n\n")
	b.WriteString("// Code generated by cmd/gen-icons — DO NOT EDIT.\n")
	b.WriteString("// Source: lucide-static (ISC) — https://lucide.dev\n")
	b.WriteString("// To add an icon: append \"templ IconNewName() {}\" then run: go run ./cmd/gen-icons\n\n")

	// Individual icon functions using <use> references into the static sprite.
	for _, d := range data {
		fmt.Fprintf(&b, "// %s renders the Lucide %q icon.\ntempl %s() {\n\t@templ.Raw(`<svg %s><use href=\"/icons.svg#%s\"></use></svg>`)\n}\n\n",
			d.name, d.file, d.name, useAttrs, iconID(d.file))
	}

	if err := os.WriteFile(path, []byte(strings.TrimRight(b.String(), "\n")+"\n"), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing icons.templ: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote", path)
}

func writeIconsJS(path string, data []iconData) {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen-icons — DO NOT EDIT.\n")
	b.WriteString("// Source: lucide-static (ISC) — https://lucide.dev\n\n")
	b.WriteString("const ICON_ATTRS = 'class=\"icon\" aria-hidden=\"true\"';\n\n")

	for _, d := range data {
		jsName := strings.ToLower(d.name[:1]) + d.name[1:] // IconPlay → iconPlay
		fmt.Fprintf(&b, "export function %s() {\n  return `<svg ${ICON_ATTRS}><use href=\"/icons.svg#%s\"></use></svg>`;\n}\n\n",
			jsName, iconID(d.file))
	}

	if err := os.WriteFile(path, []byte(strings.TrimRight(b.String(), "\n")+"\n"), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing icons.js: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote", path)
}

func findRoot() string {
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "go.mod not found")
			os.Exit(1)
		}
		dir = parent
	}
}
