// Code generated by cmd/gen-icons — DO NOT EDIT.
// Source: lucide-static (ISC) — https://lucide.dev

const ICON_ATTRS = 'class="icon" aria-hidden="true"';

export function iconPlay() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-play"></use></svg>`;
}

export function iconCircle() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-circle"></use></svg>`;
}

export function iconGripVertical() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-grip-vertical"></use></svg>`;
}

export function iconArrowUpRight() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-arrow-up-right"></use></svg>`;
}

export function iconExternalLink() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-external-link"></use></svg>`;
}

export function iconX() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-x"></use></svg>`;
}

export function iconRepeat() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-repeat"></use></svg>`;
}

export function iconShuffle() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-shuffle"></use></svg>`;
}

export function iconSkipBack() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-skip-back"></use></svg>`;
}

export function iconRewind() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-rewind"></use></svg>`;
}

export function iconFastForward() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-fast-forward"></use></svg>`;
}

export function iconSkipForward() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-skip-forward"></use></svg>`;
}

export function iconRefreshCw() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-refresh-cw"></use></svg>`;
}

export function iconPencil() {
  return `<svg ${ICON_ATTRS}><use href="/icons.svg#icon-pencil"></use></svg>`;
}
